### ISSUE TITLE
LNTILING

### ISSUE THREAD

**Issue by highcliff** [him0727/Online-Judge-Solutions#1]
I'm curious... how many people have submitted your own solution to your LNTILING problem?

**Comment by him0727** [comment]
> I'm curious... how many people have submitted your own solution to your LNTILING problem?

Approximately 30 - 40% submissions are copied directly or just with some minor changes, eg. indentation, variable name..

**Comment by highcliff** [comment]
As many as that! I guess that can't bother you, or else you'd not make your solution public. Do you disqualify those entries that are a copy?

**Comment by him0727** [comment]
> As many as that! I guess that can't bother you, or else you'd not make your solution public. Do you disqualify those entries that are a copy?

Yes I disqualified those submission and will keep monitoring. It doesn't bother me but unfair to others, and people can only make greater progress by solving problems on their own.

**Comment by highcliff** [comment]
Thanks for replying. My reason for asking was that I was looking at the submissions of the people who appear in the "Top Coders" list on the front page of SPOJ. Some of these have many AC submissions to multiple problems only seconds apart, which suggests the solutions are being copied from somewhere. I happened to notice LNTILING for one of them (www.spoj.com/status/LNTILING,kuba935/) and was wondering whether that was yet another good problem ruined by having a solution available online.

> ...and people can only make greater progress by solving problems on their own.
Very true. I wonder then, why do you choose to publish your solutions here? I've noticed that many people do, but IMHO, this spoils SPOJ when so many people appear to be happy so simply copy'n'paste solutions.

**Comment by him0727** [comment]
> Thanks for replying. My reason for asking was that I was looking at the submissions of the people who appear in the "Top Coders" list on the front page of SPOJ. Some of these have many AC submissions to multiple problems only seconds apart, which suggests the solutions are being copied from somewhere. I happened to notice LNTILING for one of them ([www.spoj.com/status/LNTILING,kuba935/](http://www.spoj.com/status/LNTILING,kuba935/)) and was wondering whether that was yet another good problem ruined by having a solution available online.
> 
> > ...and people can only make greater progress by solving problems on their own.
> > Very true. I wonder then, why do you choose to publish your solutions here? I've noticed that many people do, but IMHO, this spoils SPOJ when so many people appear to be happy so simply copy'n'paste solutions.

SPOJ is mainly for learning purpose, just like Leetcode, we can find the official editorial easily. I think it is fine to publish code as long as those problems are not from an on-going contest. Sometimes reading code is easier than reading tutorial, so I hope this will help others when they are stuck on a problem. Of course, I trust they will not copy my solutions. And I also expect that everybody to implement themselves after reading my code. But again, I will keep monitoring so don't worry.
